A more complete notebook can be found [here](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/python/tutorial.ipynb)

In [4]:
import mujoco
import mujoco_viewer

# scene.xml includes the robot model and a simple environment
model = mujoco.MjModel.from_xml_path("../unitree_go1/scene.xml")

# Contains the state of the model (time: .time, pos: .qpos, vel: .qvel) 
data = mujoco.MjData(model)

In [5]:
# Print out the name of the body accessors
try:
    model.geom()
except KeyError as e:
    print(f"model.geom: {e}")
    
try:
    data.geom()
except KeyError as e:
    print(f"data.geom: {e}")
    
try:
    data.body()
except KeyError as e:
    print(f"data.body: {e}")

model.geom: "Invalid name ''. Valid names: ['FL', 'FR', 'RL', 'RR', 'floor']"
data.geom: "Invalid name ''. Valid names: ['FL', 'FR', 'RL', 'RR', 'floor']"
data.body: "Invalid name ''. Valid names: ['FL_calf', 'FL_hip', 'FL_thigh', 'FR_calf', 'FR_hip', 'FR_thigh', 'RL_calf', 'RL_hip', 'RL_thigh', 'RR_calf', 'RR_hip', 'RR_thigh', 'trunk', 'world']"


In [3]:
model.geom("FL")

<_MjModelGeomViews
  bodyid: array([7])
  conaffinity: array([1])
  condim: array([6])
  contype: array([1])
  dataid: array([-1])
  friction: array([0.8 , 0.02, 0.01])
  gap: array([0.])
  group: array([3])
  id: 31
  margin: array([0.001])
  matid: array([-1])
  name: 'FL'
  pos: array([ 0.   ,  0.   , -0.213])
  priority: array([1])
  quat: array([1., 0., 0., 0.])
  rbound: array([0.023])
  rgba: array([0.5, 0.5, 0.5, 1. ], dtype=float32)
  sameframe: array([0], dtype=uint8)
  size: array([0.023, 0.   , 0.   ])
  solimp: array([0.015, 1.   , 0.031, 0.5  , 2.   ])
  solmix: array([1.])
  solref: array([0.02, 1.  ])
  type: array([2])
  user: array([], dtype=float64)
>

In [4]:
print(f"Simulated time: {data.time} sec")
print(f"Default timestep: {model.opt.timestep} sec")
print(f"Degrees of freedom: {model.nv=}")

# Position has 1 extra dimension since orientation is represented with
# quaternions (4-values) while angular velocity has 3 values.
print(f"{len(data.qpos)=} {data.qpos=}")
print(f"{len(data.qvel)=} {data.qvel=}")

Simulated time: 0.0 sec
Default timestep: 0.002 sec
Degrees of freedom: model.nv=18
len(data.qpos)=19 data.qpos=array([0.   , 0.   , 0.445, 1.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   ])
len(data.qvel)=18 data.qvel=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])


In [25]:
import numpy as np
# Setup viewer
viewer = mujoco_viewer.MujocoViewer(model, data)

# Reset the simulation
mujoco.mj_resetDataKeyframe(model, data, 0)

data.qpos[4] = np.deg2rad(15)
for _ in range(1000):
    if viewer.is_alive:
        mujoco.mj_step(model, data)
        viewer.render()
        # 6 arrays, each with 14 values
        print(f"{len(data.cfrc_ext[0])=} {data.cfrc_ext[0][0].shape=} {data.cfrc_ext}")
    else:
        break

viewer.close()

len(data.cfrc_ext[0])=6 data.cfrc_ext[0][0].shape=() [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
len(data.cfrc_ext[0])=6 data.cfrc_ext[0][0].shape=() [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
len(data.cfrc_ext[0])=6 data.cfrc_ext[0][0].shape=() [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]

KeyboardInterrupt: 